services:
  runtime-pc:
    image: lwir-runtime-pc:dxas-5749ab70-ubuntu22.04

    volumes:
      - .:/workspace/lwir-npu-tracking-system
      - runtime-build:/workspace/lwir-npu-tracking-system/runtime/build

    working_dir: /workspace/lwir-npu-tracking-system/runtime

    entrypoint: /bin/bash

    stdin_open: true
    tty: true

volumes:
  runtime-build:
