logging:
  level: debug

detector:
  type: yolov8
  backend: deepx
  config: config/model/yolov8n.yaml

tracking:
  type: bytetrack
  config: config/tracking/bytetrack.yaml

control:
  enabled: false
  config: config/control.yaml

measurement:
  enabled: false
